### PR TITLE
fixed  translations

### PR DESCRIPTION
**Pull request by LNDDYL**
Chinese Trad.

### CODE REVIEW

**Comment by hfhchan** [comment]
@kenlunde I can confirm the changes in terminology are more accurate for traditional Chinese areas. Notably, 信息 is the translation for "message" and 資訊 is for "information" in Taiwan and Hong Kong.

**Comment by LNDDYL** [comment]
@hfhchan
"訊息" is the translation for "message" in Taiwan and Hong Kong.

**Comment by hfhchan** [comment]
@LNDDYL  I meant message as in the content or meaning of a speech or story, which would be translated as 信息 (as in 作者帶出一個重要信息).  In the case of a message as in an instant message or SMS, then 訊息 is indeed the correct translation.

**Comment by kenlunde** [comment]
@LNDDYL: Thank you for the contribution. As soon as I confirm that the changes look good, I will reflect them in the [Source Han Sans](https://github.com/adobe-fonts/source-han-sans/) repository.

**Pull request merged**
