### PR TITLE
Create README.jp.md

### PR DESCRIPTION
**Pull request by shinriyo**
Add Japanese README.
The project is for Japanese and Korean and Chinese.
So, why don't you create these countries' README files?
Almost Japanese can't read English well.

### CODE REVIEW

**Comment by kenlunde** [comment]
Thank you for this contribution. I compared both pull requests, and the other one, which is newer, introduced a markdown syntax error in how _makeotf_ and _otf2otc_ are italicized. I will close that pull request now, and will eventually close this pull request, because I will instead append the Japanese version to the primary _README.md_ file, like was done for the [_Source Han Code JP_](https://github.com/adobe-fonts/source-han-code-jp) repository. I also need to make some editorial and typographic changes to the text that you supplied (such as the katakana used to express my family name).

**Comment by kenlunde** [comment]
@shinriyo: Instead of doing what I described above, do you mind if I modify (edit) your pull request before accepting it? There are several things that I need to change or correct.

**Comment by shinriyo** [comment]
I don't mind your modifying.
Thank you.

**Comment by kenlunde** [comment]
In case you didn't notice, that is exactly what I did about 10 hours ago.

**Pull request merged**
